Main/urls.py
from django.urls import path
from Main import views

urlpatterns = [
    path('', views.index, name='index', ),
    path('search/', views.search_quote, name='search', ),
    path('quote/list/', views.show_list_quote, name='show_list_quote', ),
    path('quote/create/', views.create_quote, name='create_quote', ),
    path('quote/<int:quote_id>/show/', views.show_quote, name='show_quote', ),
    path('tag/list/', views.show_list_tag, name='show_list_tag', ),
    path('tag/<int:tag_id>/show/', views.show_tag, name='show_tag', ),
    path('author/list/', views.show_list_author, name='show_list_author', ),
    path('author/<int:author_id>/show/', views.show_author, name='show_author', ),
    path('403/', views.handler403, name='403', ),
    path('404/', views.handler404, name='404', ),
]

Main/models.py
from django.db import models

######################################################################################################################


class Tag(models.Model):
    id = models.AutoField(
        primary_key=True
    )
    title = models.CharField(
        verbose_name='Название тематики',
        max_length=64,
        default='',
    )
    count_quote = models.IntegerField(
        verbose_name='Количество цитат в этой тематике',
        default=0,
    )

    def __str__(self):
        return '{0}'.format(self.title)

    class Meta:
        ordering = '-count_quote', 'title',
        verbose_name = 'Тематика'
        verbose_name_plural = 'Тематики'
        managed = True


######################################################################################################################


class Author(models.Model):
    id = models.AutoField(
        primary_key=True
    )
    name = models.CharField(
        verbose_name='ФИО автора',
        max_length=256,
        default='',
    )
    count_quote = models.IntegerField(
        verbose_name='Количество цитат у автора',
        default=0,
    )

    def __str__(self):
        return '{0}'.format(self.name)

    class Meta:
        ordering = '-count_quote', 'name',
        verbose_name = 'Автор'
        verbose_name_plural = 'Авторы'
        managed = True


######################################################################################################################


class Quote(models.Model):
    id = models.AutoField(
        primary_key=True
    )
    author = models.ForeignKey(
        Author,
        verbose_name='Автор цитаты',
        blank=False,
        default=None,
        related_name='Author',
        on_delete=models.CASCADE,
    )
    quote = models.TextField(
        blank=False,
    )
    create_date = models.DateTimeField(
        verbose_name='Дата добавления цитаты',
        auto_now_add=True,
        null=True,
    )

    def get_tags(self):
        """
        Возвращает запрос к таблице Tag с тематикой для выбранной цитаты
        :return:
        """
        return Tag.objects.filter(TagQuote__quote=self)

    def __str__(self):
        return '{0}. {1}...'.format(self.author, self.quote[:60])

    class Meta:
        ordering = 'author', 'create_date',
        verbose_name = 'Цитата'
        verbose_name_plural = 'Цитаты'
        managed = True

######################################################################################################################


class QuoteTag(models.Model):
    id = models.AutoField(
        primary_key=True
    )
    quote = models.ForeignKey(
        Quote,
        verbose_name='Цитата',
        null=True,
        blank=True,
        default=None,
        related_name='QuoteTag',
        on_delete=models.CASCADE,
    )
    tag = models.ForeignKey(
        Tag,
        verbose_name='Тематика',
        null=True,
        blank=True,
        default=None,
        related_name='TagQuote',
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return '{0}. {1}'.format(self.tag, self.quote)

    class Meta:
        ordering = 'tag', 'quote',
        verbose_name = 'Тематика цитаты'
        verbose_name_plural = 'Тематики цитат'
        managed = True


######################################################################################################################

Main/forms.py
from django import forms
from Main.models import Author, Quote

######################################################################################################################


class FormAuthor(forms.ModelForm):
    class Meta:
        model = Author
        fields = [
            'name',
        ]
        labels = {
            'name': 'Автор цитаты',
        }
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Укажите автора цитаты',
                }
            )
        }


######################################################################################################################


class FormQuote(forms.ModelForm):
    tag = forms.CharField(
        label='Тематики',
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control',
                'placeholder': 'Введите тематики цитаты через запятую', }
        ),
        required=True,
    )

    class Meta:
        model = Quote
        fields = [
            'quote',
        ]
        labels = {
            'quote': 'Текст цитаты',
        }
        widgets = {
            'quote': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Напишите текст цитаты',
                }
            ),
        }


######################################################################################################################

templates/quote/create.html
{% extends "base.html" %}{% load static %}
{% block html_head %}
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'js/autocomplete.js' %}"></script>
{% endblock %}
{% block html_main %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
    <div class="quote-content">
        <form method='post' action='' class="mb-0">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-12 mb-2">
                    <h6>{{ form_author.name.label }}:</h6>
                    {{ form_author.name }}
                </div>
            </div>
            {% for field in form_quote %}
                <div class="row">
                    <div class="col-md-12 mb-2">
                        <h6>{{ field.label }}:</h6>
                        {{ field }}
                    </div>
                </div>
            {% endfor %}
            <button class="btn btn-success" type="submit">Сохранить</button>
        </form>
    </div>
    <script>
        $( "#id_name" ).on( "keydown", function( event ) {
            if ( event.keyCode === $.ui.keyCode.TAB &&
                $( this ).autocomplete( "instance" ).menu.active ) {
                event.preventDefault();
            }
        }).autocomplete({
            source: {{ list_author | safe }}
        });

        $( "#id_tag" ).on( "keydown", function( event ) {
            if ( event.keyCode === $.ui.keyCode.TAB &&
                $( this ).autocomplete( "instance" ).menu.active ) {
                event.preventDefault();
            }
        }).autocomplete({
            minLength: 0,
            source: function( request, response ) {
                response( $.ui.autocomplete.filter(
                    {{ list_tag | safe }}, extractLast( request.term ) )
                );
            },
            focus: function() {
                return false;
            },
            select: function( event, ui ) {
                let terms = split( this.value );
                terms.pop();
                terms.push( ui.item.value );
                terms.push( "" );
                this.value = terms.join( ", " );
                return false;
            }
        });
    </script>
{% endblock %}

templates/quote/list.html
{% extends "base.html" %}{% load static %}
{% block html_head %}
    <script src="{% static 'js/highlight.js' %}"></script>
{% endblock %}
{% block html_main %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
    <div class="quote-content" id="quote-content">
        {% for quote in quotes %}
            {% include "quote/quote.html" %}
        {% endfor %}
    </div>
    {% if search %}
        <script>
            highlight("{{ search }}");
        </script>
    {% endif %}
{% endblock %}

templates/quote/quote.html
            <div class="quote-post">
                <div class="quote-text">
                    {{ quote.quote }}
                </div>
                <div class="row">
                    <div class="col-auto mr-auto"></div>
                    <div class="col-auto mr-0 text-right">
                        <div class="quote-author">
                            <a href="{% url 'show_author' quote.author.id %}">{{ quote.author }}</a>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-auto mr-auto">
                        <div class="quote-tag">
                            <ul>
                                {% for tag in quote.get_tags %}
                                    <li>
                                        <a href="{% url 'show_tag' tag.id %}" class="btn btn-outline-success" role="button" aria-pressed="true">{{ tag.title }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="col-auto mr-0 text-right">
                        <div class="quote-share">
                            <div class="ya-share2" data-curtain data-limit="0" data-more-button-type="short" data-popup-position="outer" data-services="vkontakte,facebook,telegram,twitter" data-description="Цитатник. Цитата - {{ quote }}" data-title="{{ quote }}" data-url="https://{{ request.META.HTTP_HOST }}{% url 'show_quote' quote.id %}"></div>
                        </div>
                    </div>
                </div>
            </div>

templates/quote/show.html
{% extends "base.html" %}{% load static %}
{% block html_main %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
    <div class="quote-content">
        {% include "quote/quote.html" %}
    </div>
{% endblock %}